# Generated by Django 5.1.6 on 2025-03-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_recipeingredient_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
    ]
