# Generated by Django 5.1.5 on 2025-04-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipeimage',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipeimage',
            old_name='Recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Ingredient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
