# Generated by Django 5.1.5 on 2025-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_rename_description_recipeimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
